<a href="https://colab.research.google.com/github/chokr0216/-2/blob/master/matrixadd_1_3_200323.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 매트릭스 덧셈 계산하기
  * 과제 1-3 하기
  

In [2]:
import numpy as np
# 텐서 생성
# 런타임 하드웨어가속도 none
a=np.array([1.0, 2.0, 3.0])
b=np.array([2.0, 4.0, 6.0])
print(a+b)

[3. 6. 9.]


In [3]:
import numpy as np
# 텐서 생성
# 런타임 하드웨어가속도 GPU
a=np.array([1.0, 2.0, 3.0])
b=np.array([2.0, 4.0, 6.0])
print(a+b)

[3. 6. 9.]


In [4]:
import numpy as np
# 텐서 생성
# 런타임 하드웨어가속도 none
a=np.array([[1.0, 2.0, 3.0], [2.0,4.0,6.0]])
b=np.array([[2.0, 4.0, 6.0],[3.5, 5.5, 7.5]])
print(a+b)

[[ 3.   6.   9. ]
 [ 5.5  9.5 13.5]]


In [5]:
import numpy as np
# 텐서 생성
# 런타임 하드웨어가속도 gpu
a=np.array([[1.0, 2.0, 3.0], [2.0,4.0,6.0]])
b=np.array([[2.0, 4.0, 6.0],[3.5, 5.5, 7.5]])
print(a+b)

[[ 3.   6.   9. ]
 [ 5.5  9.5 13.5]]
